### ISSUE TITLE
Something wrong when click the ip

### ISSUE THREAD

**Issue by xxnbyy** [Rev3rseSecurity/WebMap#35]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including the Nmap syntax used:

1. Nmap syntax: nmap -v -p- -sV -iL ip.txt -oX 1.xml
2. WebMap in docker container: [x] Yes / [ ] No
3. WebMap version or branch: ... (example: v2.1/master)
3. Step to reproduce: Import a xml file,and load it,when click the ip ,the wrong happen.

**Expected behavior**
Import a xml file,and load it,when click the ip ,the wrong happen.

**Screenshots**
![default](https://user-images.githubusercontent.com/20261647/48879174-8bc68f00-ee45-11e8-8fa2-93aab15449a9.png)

![default](https://user-images.githubusercontent.com/20261647/48879075-3c805e80-ee45-11e8-9913-2aac9f2e1451.png)

**Comment by xxnbyy** [comment]
And olny the first one is wrong ,others is great

**Comment by theMiddleBlue** [comment]
hi @xxnbyy 

thanks for reporting this. This issue is already fixed on 2.2/master version, and the new webmap 2.2 docker image will be available soon on dockerhub. I'll close this issue when done.

Thanks!

**Comment by theMiddleBlue** [comment]
Hi @xxnbyy 

the v2.2 is out, can you try to reinstall WebMap with:
`curl -sL http://bit.ly/webmapsetup | bash`

let me know if it solve your issue.

**Comment by xxnbyy** [comment]
Ok,thanks

**Comment by xxnbyy** [comment]
@theMiddleBlue The bug of click service is fixed ,but when i click some ip report ,it's still wrong.
![default](https://user-images.githubusercontent.com/20261647/48935024-2061e780-ef41-11e8-9600-8fff8cf2d321.png)
![default](https://user-images.githubusercontent.com/20261647/48935092-5901c100-ef41-11e8-9162-1696ba62181d.png)

**Comment by theMiddleBlue** [comment]
hi @xxnbyy I've just updated the docker image with this new fix, could you try to update your webmap?
as usual with:

`curl -sL http://bit.ly/webmapsetup | bash`

thanks

**Comment by theMiddleBlue** [comment]
> And i have another advice ,the short link created by http://bit.ly/ can't visit in China ,it's be blocked ,maybe you can try another one.:)

ouch, didn't know it... 

ok, probably I've fixed (it would be nice if you can redact and share your xml file):
`curl -s 'https://rev3rse.it/webmap.txt' | bash` 👍

**Comment by xxnbyy** [comment]
Ok,Here is the xml file ,and i had cover the real ip is ,the bug is still in,you can try it
[2.zip](https://github.com/Rev3rseSecurity/WebMap/files/2611196/2.zip)

**Comment by theMiddleBlue** [comment]
thanks, downloaded. I'm browsing all hosts but I can't reproduce the issue with the latest WebMap version... any hint on how to trigger the error?

**Comment by xxnbyy** [comment]
it's relally strange, just put the xml file to /tmp/webmap and open the website,click the first one ip ,there is 192.168.1.1,the bug happend.

**Comment by theMiddleBlue** [comment]
I'm testing all section and found others bugs :( 
come back when all fix are done!

**Comment by theMiddleBlue** [comment]
ok, tested your xml on:

- scan list
- host list
- host details
- pdf view
- WebMap API
- CVE API

all seems working without error. I've just updated the docker image on dockerhub.
